apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  MONGO_INITDB_ROOT_USERNAME: dXNlcm5hbWU=
kind: Secret
metadata:
  name: mongodb-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-depl
  name: mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-depl
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-depl
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
              name: mongodb-secret

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-depl
  name: mongodb-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo-depl
status:
  loadBalancer: {}
